[tool.poetry]
name = "update-members"
version = "0.1.0"
description = ""
authors = ["jcable <julian.cable@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
bng-latlon = "^1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
